FROM neurodebian:xenial

#Base installs
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	freesurfer \
	fsl 

#Move minimal simnibs components over

#Define minimal environment for running mri2mesh

